CC=gcc
CFLAGS=-g -Wall -lm
all:	program
program: test.c picomms.c mapping.c basicFunctions.c linkedList.c dijkstra.c
	$(CC) $(CFLAGS) -o test test.c picomms.c mapping.c basicFunctions.c linkedList.c dijkstra.c  -lm