CC = gcc
CFLAGS = -g -Wall
Task4: Task4.c picomms.c mapping.c wallfollower.c linkedList.c basicFunctions.c
	$(CC) $(CFLAGS) -o Task4 Task4.c picomms.c mapping.c wallfollower.c linkedList.c basicFunctions.c -lm