CC=gcc
CFLAGS=-g -Wall -lm
all:	program
program: task4.c picomms.c mapping.c wallfollower.c basicFunctions.c linkedList.c
	$(CC) $(CFLAGS) -o Task4 task4.c picomms.c mapping.c wallfollower.c basicFunctions.c linkedList.c -lm