CC=gcc
CFLAGS=-g -Wall -lm
all:	program
program: Task5.c picomms.c mapping.c basicFunctions.c linkedList.c trace.c wallfollower.c
	$(CC) $(CFLAGS) -o Task5 Task5.c picomms.c mapping.c basicFunctions.c linkedList.c trace.c wallfollower.c -lm